# Site settings
title: आरती संग्रह | Aarti Sangrah
description: Complete collection of Marathi Aartis with lyrics, audio and video
url: "https://deepakmahakale.com"
baseurl: "/aarti"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  aartis:
    output: true
    permalink: /aarti/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Language settings
lang: mr
locale: mr_IN

# SEO optimization
author: Aarti Sangrah Team
# twitter:
#   username: aarti collection
#   card: summary_large_image

facebook:
  app_id:
  publisher:
  admins:

logo: /assets/images/logo.png

# social:
#   name: Aarti Collection
#   links:
#     - https://www.facebook.com/aarticollection
#     - https://www.twitter.com/aarticollection

# Default front matter
defaults:
  - scope:
      path: ""
      type: "aartis"
    values:
      layout: "aarti"
      author: "Aarti Sangrah"
      image: "/assets/images/default-aarti.jpg"